#!/bin/bash

#!/bin/bash
# Init
FILE=`mktemp`
GREP="/bin/grep"
#....
# Make sure only root can run our script
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   rm $FILE
   exit 1
fi

rm $FILE
# ...

noarg=true
mode=

if [[ $# < 1 ]]; then
	mode=help
else
	key="$1"

	case $key in
		-i|--install)
			mode=install
			shift # past argument
			;;

		-u|--uninstall)
			mode=uninstall
			shift # past argument
			;;

		-h|--help)
			mode=help
			shift # past argument
			;;

		*)
			mode=help
			;;
	esac
fi

if [[ $mode == "help" ]]; then
	echo "Usage: kana-p-poison OPTION"
	echo ""
	echo "Arguments:"
	echo "  -i, --install          Poison system with kana-p"
	echo "  -u, --uninstall        Unpoison system"
	echo "  -h, --help             display this help"
	echo ""
	echo "### Kana-p"


elif [[ $mode == "install" ]]; then
	echo "### Kana-p - poison"
	echo ""

	# Services
	systemctl enable lightdm.service > /dev/null
	systemctl enable NetworkManager.service > /dev/null
	systemctl enable bluetooth.service > /dev/null
  
	# Drivers
	modprobe btusb

	# LightDM
	sed -i "s#^\#display-setup-script=.*\$#display-setup-script=/usr/bin/kana-p-screen -d#g" /etc/lightdm/lightdm.conf
	sed -i "s#^\#greeter-session=.*\$#greeter-session=lightdm-webkit2-greeter#g" /etc/lightdm/lightdm.conf
	#sed -i "s#^background_images *=.*\$#background_images = /usr/share/backgrounds/#g" /etc/lightdm/lightdm-webkit2-greeter.conf
	sed -i "s#^webkit_theme *=.*\$#webkit_theme        = Bevel#g" /etc/lightdm/lightdm-webkit2-greeter.conf
	sed -i "s#-blur 0x3 #-scale 5% -scale 2000% #g" /usr/bin/i3lock-wrapper

elif [[ $mode == "uninstall" ]]; then
	echo "### Kana-p - unpoison"
	echo ""

	# Services
	systemctl disable lightdm.service > /dev/null
	systemctl disable NetworkManager.service > /dev/null
	systemctl disable bluetooth.service > /dev/null

	# LightDM
	sed -i "s#display-setup-script=/usr/bin/kana-p-screen -d#\#display-setup-script=#g" /etc/lightdm/lightdm.conf
	sed -i "s#^greeter-session=lightdm-webkit2-greeter\$#\#greeter-session=#g" /etc/lightdm/lightdm.conf
	#sed -i 's#^background_images *= */usr/share/backgrounds/$#background_images =#g' /etc/lightdm/lightdm-webkit2-greeter.conf
	sed -i "s#^webkit_theme *= *Bevel\$#webkit_theme        = webkit#g" /etc/lightdm/lightdm-webkit2-greeter.conf
	sed -i "s#-scale 5% -scale 2000% #-blur 0x3 #g" /usr/bin/i3lock-wrapper
fi
